### ISSUE TITLE
Is it safe to use this in an application?

### ISSUE THREAD

**Issue by hspaay** [zenhack/go-websocket-capnp#2]
Hi,thanks for putting this together.
I'd like to use this in my hiveot project. What are your thoughts on this?
If okay, would it be good to do a release of this?

**Comment by zenhack** [comment]
I'm using it in tempest.

Wrt. a release, before stabilizing the API I'd like to gain enough experience with it to identify other shortcomings like #3. If it's not API stability guarantees you're looking for, just use the latest commit.

**Comment by hspaay** [comment]
Yep that works for me. The capnp api isn't final either so maybe the best time is to wait until capnp is.
Thanks
